[package]
name = "revvy02/netpass"
description = "Library for passing tables with instance keys across the network boundary"
version = "0.1.3"
license = "MIT"
authors = ["revvy02"]
realm = "shared"
registry = "https://github.com/upliftgames/wally-index"

exclude = ["**"]
include = ["src", "src/**", "wally.toml", "default.project.json", "LICENSE"]

[dependencies]
MockNetwork = "revvy02/mocknetwork@1.4.1"
TestEZ = "roblox/testez@0.4.1"